import '../globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning={true}
        className={`${poppins.className} bg-gray-100 min-h-screen  mt-10`}
      >
        <main className='flex flex-col justify-center items-center min-h-[80vh]'>
          {children}
        </main>
      </body>
    </html>
  );
}
